import "leaflet/dist/leaflet.css"; // 🌍 HARİTA CSS
import "./globals.css"; // ✅ Tailwind için şart
import { Header } from "@/components/Header"; // 🔥 Header eklendi
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        {/* LOGO + Menü buraya geldi */}
        <Header />
        {children}
      </body>
    </html>
  );
}
